// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.QuartzComposerChart {
	using Monobjc;
	using Monobjc.AppKit;
	using Monobjc.Quartz;
	
	
	public partial class AppController {
		
		partial void AddEntry(Id sender);

		partial void RemoveEntry(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("tableView")]
		public virtual NSTableView tableView {
			get {
				return this.GetInstanceVariable <NSTableView>("tableView");
			}
			set {
				this.SetInstanceVariable <NSTableView>("tableView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("view")]
		public virtual QCView view {
			get {
				return this.GetInstanceVariable <QCView>("view");
			}
			set {
				this.SetInstanceVariable <QCView>("view", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("addEntry:")]
		public virtual void __AddEntry(Id sender) {
			this.AddEntry(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("removeEntry:")]
		public virtual void __RemoveEntry(Id sender) {
			this.RemoveEntry(sender);
		}
	}
}
