// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.MyRecorder {
	using Monobjc;
	using Monobjc.QTKit;
	
	
	public partial class MyRecorderController {
		
		partial void StartRecording(Id sender);

		partial void StopRecording(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("mCaptureView")]
		public virtual QTCaptureView mCaptureView {
			get {
				return this.GetInstanceVariable <QTCaptureView>("mCaptureView");
			}
			set {
				this.SetInstanceVariable <QTCaptureView>("mCaptureView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("startRecording:")]
		public virtual void __StartRecording(Id sender) {
			this.StartRecording(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("stopRecording:")]
		public virtual void __StopRecording(Id sender) {
			this.StopRecording(sender);
		}
	}
}
