// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.PDFKitViewer {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppDelegate {
		
		[IBOutlet()]
		[ObjectiveCIVar("_findPanel")]
		public virtual NSPanel _findPanel {
			get {
				return this.GetInstanceVariable <NSPanel>("_findPanel");
			}
			set {
				this.SetInstanceVariable <NSPanel>("_findPanel", value);
			}
		}
	}
}
