// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SplitView {
	using Monobjc;
	using System;
	
	
	public partial class NSDocument {
		
		partial void PrintDocument(IntPtr sender);

		partial void RevertDocumentToSaved(IntPtr sender);

		partial void RunPageLayout(IntPtr sender);

		partial void SaveDocument(IntPtr sender);

		partial void SaveDocumentAs(IntPtr sender);

		partial void SaveDocumentTo(IntPtr sender);

		[IBAction()]
		[ObjectiveCMessage("printDocument:")]
		public virtual void __PrintDocument(IntPtr sender) {
			this.PrintDocument(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("revertDocumentToSaved:")]
		public virtual void __RevertDocumentToSaved(IntPtr sender) {
			this.RevertDocumentToSaved(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("runPageLayout:")]
		public virtual void __RunPageLayout(IntPtr sender) {
			this.RunPageLayout(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("saveDocument:")]
		public virtual void __SaveDocument(IntPtr sender) {
			this.SaveDocument(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("saveDocumentAs:")]
		public virtual void __SaveDocumentAs(IntPtr sender) {
			this.SaveDocumentAs(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("saveDocumentTo:")]
		public virtual void __SaveDocumentTo(IntPtr sender) {
			this.SaveDocumentTo(sender);
		}
	}
}
