// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SplitView {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class SplitViewAppDelegate {
		
		[IBOutlet()]
		[ObjectiveCIVar("labelAlignedToTopOfYellowView")]
		public virtual NSTextField labelAlignedToTopOfYellowView {
			get {
				return this.GetInstanceVariable <NSTextField>("labelAlignedToTopOfYellowView");
			}
			set {
				this.SetInstanceVariable <NSTextField>("labelAlignedToTopOfYellowView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("splitView")]
		public virtual NSView splitView {
			get {
				return this.GetInstanceVariable <NSView>("splitView");
			}
			set {
				this.SetInstanceVariable <NSView>("splitView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("window")]
		public virtual NSWindow window {
			get {
				return this.GetInstanceVariable <NSWindow>("window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("window", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("yellowLabel")]
		public virtual NSTextField yellowLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("yellowLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("yellowLabel", value);
			}
		}
	}
}
