// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.CroppedImage {
	using Monobjc;
	
	
	public partial class CroppingImageView {
		
		partial void TakeAntiAliasModeFrom(Id sender);

		partial void TakeContinuousModeFrom(Id sender);

		partial void TakeSelectionColorFrom(Id sender);

		partial void TakeSelectionMarkerStyleFrom(Id sender);

		[IBAction()]
		[ObjectiveCMessage("takeAntiAliasModeFrom:")]
		public virtual void __TakeAntiAliasModeFrom(Id sender) {
			this.TakeAntiAliasModeFrom(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("takeContinuousModeFrom:")]
		public virtual void __TakeContinuousModeFrom(Id sender) {
			this.TakeContinuousModeFrom(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("takeSelectionColorFrom:")]
		public virtual void __TakeSelectionColorFrom(Id sender) {
			this.TakeSelectionColorFrom(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("takeSelectionMarkerStyleFrom:")]
		public virtual void __TakeSelectionMarkerStyleFrom(Id sender) {
			this.TakeSelectionMarkerStyleFrom(sender);
		}
	}
}
