// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net.monobjc.samples.DraggingAndWindowResize {
	using Monobjc;
	using Monobjc.AppKit;
	using net.monobjc.samples.DraggingAndWindowResize;
	
	
	public partial class DraggingAndWindowResizeAppDelegate {
		
		[IBOutlet()]
		[ObjectiveCIVar("contentView")]
		public virtual NSView contentView {
			get {
				return this.GetInstanceVariable <NSView>("contentView");
			}
			set {
				this.SetInstanceVariable <NSView>("contentView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("resizableView")]
		public virtual ResizableView resizableView {
			get {
				return this.GetInstanceVariable <ResizableView>("resizableView");
			}
			set {
				this.SetInstanceVariable <ResizableView>("resizableView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("window")]
		public virtual NSWindow window {
			get {
				return this.GetInstanceVariable <NSWindow>("window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("window", value);
			}
		}
	}
}
