// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.ToolbarSample {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class Controller {
		
		partial void BlueText(Id sender);

		partial void ChangeFontSize(Id sender);

		partial void ChangeFontStyle(Id sender);

		partial void FontSizeBigger(Id sender);

		partial void FontSizeSmaller(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("contentView")]
		public virtual NSTextView contentView {
			get {
				return this.GetInstanceVariable <NSTextView>("contentView");
			}
			set {
				this.SetInstanceVariable <NSTextView>("contentView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fontSizeField")]
		public virtual NSTextField fontSizeField {
			get {
				return this.GetInstanceVariable <NSTextField>("fontSizeField");
			}
			set {
				this.SetInstanceVariable <NSTextField>("fontSizeField", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fontSizeMenu")]
		public virtual NSMenu fontSizeMenu {
			get {
				return this.GetInstanceVariable <NSMenu>("fontSizeMenu");
			}
			set {
				this.SetInstanceVariable <NSMenu>("fontSizeMenu", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fontSizeStepper")]
		public virtual NSStepper fontSizeStepper {
			get {
				return this.GetInstanceVariable <NSStepper>("fontSizeStepper");
			}
			set {
				this.SetInstanceVariable <NSStepper>("fontSizeStepper", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fontSizeView")]
		public virtual NSView fontSizeView {
			get {
				return this.GetInstanceVariable <NSView>("fontSizeView");
			}
			set {
				this.SetInstanceVariable <NSView>("fontSizeView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fontStyleMenu")]
		public virtual NSMenu fontStyleMenu {
			get {
				return this.GetInstanceVariable <NSMenu>("fontStyleMenu");
			}
			set {
				this.SetInstanceVariable <NSMenu>("fontStyleMenu", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popUpView")]
		public virtual NSView popUpView {
			get {
				return this.GetInstanceVariable <NSView>("popUpView");
			}
			set {
				this.SetInstanceVariable <NSView>("popUpView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("theWindow")]
		public virtual NSWindow theWindow {
			get {
				return this.GetInstanceVariable <NSWindow>("theWindow");
			}
			set {
				this.SetInstanceVariable <NSWindow>("theWindow", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("blueText:")]
		public virtual void __BlueText(Id sender) {
			this.BlueText(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("changeFontSize:")]
		public virtual void __ChangeFontSize(Id sender) {
			this.ChangeFontSize(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("changeFontStyle:")]
		public virtual void __ChangeFontStyle(Id sender) {
			this.ChangeFontStyle(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("fontSizeBigger:")]
		public virtual void __FontSizeBigger(Id sender) {
			this.FontSizeBigger(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("fontSizeSmaller:")]
		public virtual void __FontSizeSmaller(Id sender) {
			this.FontSizeSmaller(sender);
		}
	}
}
