// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.TLayer {
	using Monobjc;
	using Monobjc.AppKit;
	using Monobjc.Samples.TLayer;
	
	
	public partial class TLayerDemo {
		
		partial void ShadowRadiusChanged(Id sender);

		partial void ToggleTransparencyLayers(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("colorWell")]
		public virtual NSColorWell colorWell {
			get {
				return this.GetInstanceVariable <NSColorWell>("colorWell");
			}
			set {
				this.SetInstanceVariable <NSColorWell>("colorWell", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("shadowOffsetView")]
		public virtual ShadowOffsetView shadowOffsetView {
			get {
				return this.GetInstanceVariable <ShadowOffsetView>("shadowOffsetView");
			}
			set {
				this.SetInstanceVariable <ShadowOffsetView>("shadowOffsetView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("shadowRadiusSlider")]
		public virtual NSSlider shadowRadiusSlider {
			get {
				return this.GetInstanceVariable <NSSlider>("shadowRadiusSlider");
			}
			set {
				this.SetInstanceVariable <NSSlider>("shadowRadiusSlider", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("tlayerView")]
		public virtual TLayerView tlayerView {
			get {
				return this.GetInstanceVariable <TLayerView>("tlayerView");
			}
			set {
				this.SetInstanceVariable <TLayerView>("tlayerView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("transparencyLayerButton")]
		public virtual NSButton transparencyLayerButton {
			get {
				return this.GetInstanceVariable <NSButton>("transparencyLayerButton");
			}
			set {
				this.SetInstanceVariable <NSButton>("transparencyLayerButton", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("shadowRadiusChanged:")]
		public virtual void __ShadowRadiusChanged(Id sender) {
			this.ShadowRadiusChanged(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("toggleTransparencyLayers:")]
		public virtual void __ToggleTransparencyLayers(Id sender) {
			this.ToggleTransparencyLayers(sender);
		}
	}
}
