// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net.monobjc.samples.Popover {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class MyViewController {
		
		partial void CheckBoxAction(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("checkButton")]
		public virtual NSButton checkButton {
			get {
				return this.GetInstanceVariable <NSButton>("checkButton");
			}
			set {
				this.SetInstanceVariable <NSButton>("checkButton", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textLabel")]
		public virtual NSTextField textLabel {
			get {
				return this.GetInstanceVariable <NSTextField>("textLabel");
			}
			set {
				this.SetInstanceVariable <NSTextField>("textLabel", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("checkBoxAction:")]
		public virtual void __CheckBoxAction(Id sender) {
			this.CheckBoxAction(sender);
		}
	}
}
