// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace net.monobjc.samples.Popover {
	using Monobjc;
	using Monobjc.AppKit;
	using Popover;
	
	
	public partial class MyWindowController {
		
		partial void ShowPopoverAction(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("animatesCheckbox")]
		public virtual NSButton animatesCheckbox {
			get {
				return this.GetInstanceVariable <NSButton>("animatesCheckbox");
			}
			set {
				this.SetInstanceVariable <NSButton>("animatesCheckbox", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("detachedHUDWindow")]
		public virtual NSPanel detachedHUDWindow {
			get {
				return this.GetInstanceVariable <NSPanel>("detachedHUDWindow");
			}
			set {
				this.SetInstanceVariable <NSPanel>("detachedHUDWindow", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("detachedWindow")]
		public virtual NSWindow detachedWindow {
			get {
				return this.GetInstanceVariable <NSWindow>("detachedWindow");
			}
			set {
				this.SetInstanceVariable <NSWindow>("detachedWindow", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("detachedWindowViewController")]
		public virtual MyViewController detachedWindowViewController {
			get {
				return this.GetInstanceVariable <MyViewController>("detachedWindowViewController");
			}
			set {
				this.SetInstanceVariable <MyViewController>("detachedWindowViewController", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("detachedWindowViewControllerHUD")]
		public virtual MyViewController detachedWindowViewControllerHUD {
			get {
				return this.GetInstanceVariable <MyViewController>("detachedWindowViewControllerHUD");
			}
			set {
				this.SetInstanceVariable <MyViewController>("detachedWindowViewControllerHUD", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popoverPosition")]
		public virtual NSMatrix popoverPosition {
			get {
				return this.GetInstanceVariable <NSMatrix>("popoverPosition");
			}
			set {
				this.SetInstanceVariable <NSMatrix>("popoverPosition", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popoverType")]
		public virtual NSMatrix popoverType {
			get {
				return this.GetInstanceVariable <NSMatrix>("popoverType");
			}
			set {
				this.SetInstanceVariable <NSMatrix>("popoverType", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popoverViewController")]
		public virtual MyViewController popoverViewController {
			get {
				return this.GetInstanceVariable <MyViewController>("popoverViewController");
			}
			set {
				this.SetInstanceVariable <MyViewController>("popoverViewController", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("popoverViewControllerHUD")]
		public virtual MyViewController popoverViewControllerHUD {
			get {
				return this.GetInstanceVariable <MyViewController>("popoverViewControllerHUD");
			}
			set {
				this.SetInstanceVariable <MyViewController>("popoverViewControllerHUD", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("showPopoverAction:")]
		public virtual void __ShowPopoverAction(Id sender) {
			this.ShowPopoverAction(sender);
		}
	}
}
