// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.Fire {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppController {
		
		partial void SlidersChanged(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("gasSlider")]
		public virtual NSSlider gasSlider {
			get {
				return this.GetInstanceVariable <NSSlider>("gasSlider");
			}
			set {
				this.SetInstanceVariable <NSSlider>("gasSlider", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("view")]
		public virtual NSView view {
			get {
				return this.GetInstanceVariable <NSView>("view");
			}
			set {
				this.SetInstanceVariable <NSView>("view", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("slidersChanged:")]
		public virtual void __SlidersChanged(Id sender) {
			this.SlidersChanged(sender);
		}
	}
}
