// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.RayTracer {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppController {
		
		partial void Compute(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("imageView")]
		public virtual NSImageView imageView {
			get {
				return this.GetInstanceVariable <NSImageView>("imageView");
			}
			set {
				this.SetInstanceVariable <NSImageView>("imageView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("compute:")]
		public virtual void __Compute(Id sender) {
			this.Compute(sender);
		}
	}
}
