// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.NSSpeechSynthesizerExample {
	using Monobjc;
	using Monobjc.Samples.NSSpeechSynthesizerExample;
	using Monobjc.AppKit;
	
	
	public partial class NSSpeechExampleWindow {
		
		partial void SavetButtonSelected(Id sender);

		partial void SpeakTextButtonSelected(Id sender);

		partial void StartStopSimpleCommandButtonSelected(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("_characterView")]
		public virtual SpeakingCharacterView _characterView {
			get {
				return this.GetInstanceVariable <SpeakingCharacterView>("_characterView");
			}
			set {
				this.SetInstanceVariable <SpeakingCharacterView>("_characterView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("_saveButton")]
		public virtual NSButton _saveButton {
			get {
				return this.GetInstanceVariable <NSButton>("_saveButton");
			}
			set {
				this.SetInstanceVariable <NSButton>("_saveButton", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("_textToSpeechExampleSpeakButton")]
		public virtual NSButton _textToSpeechExampleSpeakButton {
			get {
				return this.GetInstanceVariable <NSButton>("_textToSpeechExampleSpeakButton");
			}
			set {
				this.SetInstanceVariable <NSButton>("_textToSpeechExampleSpeakButton", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("_textToSpeechExampleTextView")]
		public virtual NSTextView _textToSpeechExampleTextView {
			get {
				return this.GetInstanceVariable <NSTextView>("_textToSpeechExampleTextView");
			}
			set {
				this.SetInstanceVariable <NSTextView>("_textToSpeechExampleTextView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("_voicePop")]
		public virtual NSPopUpButton _voicePop {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("_voicePop");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("_voicePop", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("_window")]
		public virtual NSWindow _window {
			get {
				return this.GetInstanceVariable <NSWindow>("_window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("_window", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("savetButtonSelected:")]
		public virtual void __SavetButtonSelected(Id sender) {
			this.SavetButtonSelected(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("speakTextButtonSelected:")]
		public virtual void __SpeakTextButtonSelected(Id sender) {
			this.SpeakTextButtonSelected(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("startStopSimpleCommandButtonSelected:")]
		public virtual void __StartStopSimpleCommandButtonSelected(Id sender) {
			this.StartStopSimpleCommandButtonSelected(sender);
		}
	}
}
