// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.DatePlot {
	using Monobjc;
	using Monobjc.CorePlot;
	
	
	public partial class Controller {
		
		partial void ExplodeLayers(Id sender);

		partial void ExportToPDF(Id sender);

		partial void ExportToPNG(Id sender);

		partial void ReassembleLayers(Id sender);

		partial void ReloadDataSourcePlot(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("hostView")]
		public virtual CPTLayerHostingView hostView {
			get {
				return this.GetInstanceVariable <CPTLayerHostingView>("hostView");
			}
			set {
				this.SetInstanceVariable <CPTLayerHostingView>("hostView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("explodeLayers:")]
		public virtual void __ExplodeLayers(Id sender) {
			this.ExplodeLayers(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("exportToPDF:")]
		public virtual void __ExportToPDF(Id sender) {
			this.ExportToPDF(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("exportToPNG:")]
		public virtual void __ExportToPNG(Id sender) {
			this.ExportToPNG(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("reassembleLayers:")]
		public virtual void __ReassembleLayers(Id sender) {
			this.ReassembleLayers(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("reloadDataSourcePlot:")]
		public virtual void __ReloadDataSourcePlot(Id sender) {
			this.ReloadDataSourcePlot(sender);
		}
	}
}
