// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace ScriptingBridgeiCal {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class Controller {
		
		partial void AddUpdateEvent(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("calendar")]
		public virtual NSTextField calendar {
			get {
				return this.GetInstanceVariable <NSTextField>("calendar");
			}
			set {
				this.SetInstanceVariable <NSTextField>("calendar", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("event")]
		public virtual NSTextField @event {
			get {
				return this.GetInstanceVariable <NSTextField>("event");
			}
			set {
				this.SetInstanceVariable <NSTextField>("event", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("time")]
		public virtual NSDatePicker time {
			get {
				return this.GetInstanceVariable <NSDatePicker>("time");
			}
			set {
				this.SetInstanceVariable <NSDatePicker>("time", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("addUpdateEvent:")]
		public virtual void __AddUpdateEvent(Id sender) {
			this.AddUpdateEvent(sender);
		}
	}
}
