// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.1
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace TutorialI18N {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppDelegate {
		
		partial void ShowAlert(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("window")]
		public virtual NSWindow window {
			get {
				return this.GetInstanceVariable <NSWindow>("window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("window", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("showAlert:")]
		public virtual void __ShowAlert(Id sender) {
			this.ShowAlert(sender);
		}
	}
}
