//
// Generated by MonoDevelop Monobjc Addins
//
// Only wired actions or outlets will be processed
//
#import <AppKit/AppKit.h>
#import <Foundation/Foundation.h>
#import <ScriptingBridge/ScriptingBridge.h>

@interface Controller : NSObject {
	IBOutlet NSTextView *commentField;
	IBOutlet NSTextField *fileNameField;
}

@end
