// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace SBSetFinderComment {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class Controller {
		
		partial void ChangeComment(Id sender);

		partial void RevealInFinder(Id sender);

		partial void SelectFileForComment(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("commentField")]
		public virtual NSTextView commentField {
			get {
				return this.GetInstanceVariable <NSTextView>("commentField");
			}
			set {
				this.SetInstanceVariable <NSTextView>("commentField", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fileNameField")]
		public virtual NSTextField fileNameField {
			get {
				return this.GetInstanceVariable <NSTextField>("fileNameField");
			}
			set {
				this.SetInstanceVariable <NSTextField>("fileNameField", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("changeComment:")]
		public virtual void __ChangeComment(Id sender) {
			this.ChangeComment(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("revealInFinder:")]
		public virtual void __RevealInFinder(Id sender) {
			this.RevealInFinder(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("selectFileForComment:")]
		public virtual void __SelectFileForComment(Id sender) {
			this.SelectFileForComment(sender);
		}
	}
}
