// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.AppList {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppController {
		
		partial void HideAction(Id sender);

		partial void QuitAction(Id sender);

		partial void UnhideAction(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("arrayController")]
		public virtual NSArrayController arrayController {
			get {
				return this.GetInstanceVariable <NSArrayController>("arrayController");
			}
			set {
				this.SetInstanceVariable <NSArrayController>("arrayController", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("hideAction:")]
		public virtual void __HideAction(Id sender) {
			this.HideAction(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("quitAction:")]
		public virtual void __QuitAction(Id sender) {
			this.QuitAction(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("unhideAction:")]
		public virtual void __UnhideAction(Id sender) {
			this.UnhideAction(sender);
		}
	}
}
