// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.SimpleWebBrowser {
	using Monobjc;
	using Monobjc.AppKit;
	using Monobjc.WebKit;
	
	
	public partial class AppController {
		
		partial void Fetch(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("indicator")]
		public virtual NSProgressIndicator indicator {
			get {
				return this.GetInstanceVariable <NSProgressIndicator>("indicator");
			}
			set {
				this.SetInstanceVariable <NSProgressIndicator>("indicator", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("urlText")]
		public virtual NSTextField urlText {
			get {
				return this.GetInstanceVariable <NSTextField>("urlText");
			}
			set {
				this.SetInstanceVariable <NSTextField>("urlText", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("webView")]
		public virtual WebView webView {
			get {
				return this.GetInstanceVariable <WebView>("webView");
			}
			set {
				this.SetInstanceVariable <WebView>("webView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("window")]
		public virtual NSWindow window {
			get {
				return this.GetInstanceVariable <NSWindow>("window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("window", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("fetch:")]
		public virtual void __Fetch(Id sender) {
			this.Fetch(sender);
		}
	}
}
