// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.MiniBooth {
	using Monobjc;
	using Monobjc.Quartz;
	using Monobjc.AppKit;
	
	
	public partial class AppController {
		
		partial void SavePNG(Id sender);

		partial void ToggleCompositionPicker(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("qcView")]
		public virtual QCView qcView {
			get {
				return this.GetInstanceVariable <QCView>("qcView");
			}
			set {
				this.SetInstanceVariable <QCView>("qcView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("window")]
		public virtual NSWindow window {
			get {
				return this.GetInstanceVariable <NSWindow>("window");
			}
			set {
				this.SetInstanceVariable <NSWindow>("window", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("savePNG:")]
		public virtual void __SavePNG(Id sender) {
			this.SavePNG(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("toggleCompositionPicker:")]
		public virtual void __ToggleCompositionPicker(Id sender) {
			this.ToggleCompositionPicker(sender);
		}
	}
}
