// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.CustomSave {
	using Monobjc;
	using Monobjc.AppKit;
	using System;
	
	
	public partial class MyDocument {
		
		partial void FilePackagesAsDirAction(IntPtr sender);

		[IBOutlet()]
		[ObjectiveCIVar("appendCheck")]
		public virtual NSButton appendCheck {
			get {
				return this.GetInstanceVariable <NSButton>("appendCheck");
			}
			set {
				this.SetInstanceVariable <NSButton>("appendCheck", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("navigatePackages")]
		public virtual NSButton navigatePackages {
			get {
				return this.GetInstanceVariable <NSButton>("navigatePackages");
			}
			set {
				this.SetInstanceVariable <NSButton>("navigatePackages", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("saveDialogCustomView")]
		public virtual NSView saveDialogCustomView {
			get {
				return this.GetInstanceVariable <NSView>("saveDialogCustomView");
			}
			set {
				this.SetInstanceVariable <NSView>("saveDialogCustomView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("soundOnCheck")]
		public virtual NSButton soundOnCheck {
			get {
				return this.GetInstanceVariable <NSButton>("soundOnCheck");
			}
			set {
				this.SetInstanceVariable <NSButton>("soundOnCheck", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("textView")]
		public virtual NSTextView textView {
			get {
				return this.GetInstanceVariable <NSTextView>("textView");
			}
			set {
				this.SetInstanceVariable <NSTextView>("textView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("filePackagesAsDirAction:")]
		public virtual void __FilePackagesAsDirAction(IntPtr sender) {
			this.FilePackagesAsDirAction(sender);
		}
	}
}
