// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.SimpleCocoaApp {
	using Monobjc;
	using Monobjc.Samples.SimpleCocoaApp;
	using Monobjc.AppKit;
	
	
	public partial class HelloController {
		
		partial void ShowHelp(Id sender);

		partial void SwitchMessage(NSMatrix sender);

		partial void SwitchObject(NSPopUpButton sender);

		[IBOutlet()]
		[ObjectiveCIVar("hello1")]
		public virtual Hello1 hello1 {
			get {
				return this.GetInstanceVariable <Hello1>("hello1");
			}
			set {
				this.SetInstanceVariable <Hello1>("hello1", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("hello2")]
		public virtual Hello2 hello2 {
			get {
				return this.GetInstanceVariable <Hello2>("hello2");
			}
			set {
				this.SetInstanceVariable <Hello2>("hello2", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("helloButton")]
		public virtual NSButton helloButton {
			get {
				return this.GetInstanceVariable <NSButton>("helloButton");
			}
			set {
				this.SetInstanceVariable <NSButton>("helloButton", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("messageRadio")]
		public virtual NSMatrix messageRadio {
			get {
				return this.GetInstanceVariable <NSMatrix>("messageRadio");
			}
			set {
				this.SetInstanceVariable <NSMatrix>("messageRadio", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("objectPopUp")]
		public virtual NSPopUpButton objectPopUp {
			get {
				return this.GetInstanceVariable <NSPopUpButton>("objectPopUp");
			}
			set {
				this.SetInstanceVariable <NSPopUpButton>("objectPopUp", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("showHelp:")]
		public virtual void __ShowHelp(Id sender) {
			this.ShowHelp(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("switchMessage:")]
		public virtual void __SwitchMessage(NSMatrix sender) {
			this.SwitchMessage(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("switchObject:")]
		public virtual void __SwitchObject(NSPopUpButton sender) {
			this.SwitchObject(sender);
		}
	}
}
