// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.SimpleCocoaApp {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class Hello1 {
		
		partial void Message1(Id sender);

		partial void Message2(Id sender);

		partial void Message3(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("messageTextField")]
		public virtual NSTextField messageTextField {
			get {
				return this.GetInstanceVariable <NSTextField>("messageTextField");
			}
			set {
				this.SetInstanceVariable <NSTextField>("messageTextField", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("message1:")]
		public virtual void __Message1(Id sender) {
			this.Message1(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("message2:")]
		public virtual void __Message2(Id sender) {
			this.Message2(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("message3:")]
		public virtual void __Message3(Id sender) {
			this.Message3(sender);
		}
	}
}
