// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.QTKitPlayer {
	using Monobjc;
	using Monobjc.QTKit;
	
	
	public partial class MyDocument {
		
		[IBOutlet()]
		[ObjectiveCIVar("mMovieView")]
		public virtual QTMovieView mMovieView {
			get {
				return this.GetInstanceVariable <QTMovieView>("mMovieView");
			}
			set {
				this.SetInstanceVariable <QTMovieView>("mMovieView", value);
			}
		}
	}
}
