// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace GLFullScreen {
	using Monobjc;
	using GLFullScreen;
	
	
	public partial class MainController {
		
		partial void GoFullScreen(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("openGLView")]
		public virtual MyOpenGLView openGLView {
			get {
				return this.GetInstanceVariable <MyOpenGLView>("openGLView");
			}
			set {
				this.SetInstanceVariable <MyOpenGLView>("openGLView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("goFullScreen:")]
		public virtual void __GoFullScreen(Id sender) {
			this.GoFullScreen(sender);
		}
	}
}
