// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.BasicCocoaAnimations {
	using Monobjc;
	
	
	public partial class AppController {
		
		partial void ShowInspector(Id sender);

		partial void ShowMainWindow(Id sender);

		[IBAction()]
		[ObjectiveCMessage("showInspector:")]
		public virtual void __ShowInspector(Id sender) {
			this.ShowInspector(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("showMainWindow:")]
		public virtual void __ShowMainWindow(Id sender) {
			this.ShowMainWindow(sender);
		}
	}
}
