// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.BasicCocoaAnimations {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class MainWindowController {
		
		partial void MoveAllViews(Id sender);

		partial void MoveView(Id sender);

		partial void SwitchView(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("imageView")]
		public virtual NSView imageView {
			get {
				return this.GetInstanceVariable <NSView>("imageView");
			}
			set {
				this.SetInstanceVariable <NSView>("imageView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("largeView")]
		public virtual NSView largeView {
			get {
				return this.GetInstanceVariable <NSView>("largeView");
			}
			set {
				this.SetInstanceVariable <NSView>("largeView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("mediumView")]
		public virtual NSView mediumView {
			get {
				return this.GetInstanceVariable <NSView>("mediumView");
			}
			set {
				this.SetInstanceVariable <NSView>("mediumView", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("smallView")]
		public virtual NSView smallView {
			get {
				return this.GetInstanceVariable <NSView>("smallView");
			}
			set {
				this.SetInstanceVariable <NSView>("smallView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("moveAllViews:")]
		public virtual void __MoveAllViews(Id sender) {
			this.MoveAllViews(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("moveView:")]
		public virtual void __MoveView(Id sender) {
			this.MoveView(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("switchView:")]
		public virtual void __SwitchView(Id sender) {
			this.SwitchView(sender);
		}
	}
}
