// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.ContentBurn {
	using Monobjc;
	
	
	public partial class AppController {
		
		partial void CreateAudioDisc(Id sender);

		partial void CreateDataDisc(Id sender);

		[IBAction()]
		[ObjectiveCMessage("createAudioDisc:")]
		public virtual void __CreateAudioDisc(Id sender) {
			this.CreateAudioDisc(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("createDataDisc:")]
		public virtual void __CreateDataDisc(Id sender) {
			this.CreateDataDisc(sender);
		}
	}
}
