// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.CocoaPeoplePicker {
	using Monobjc;
	using Monobjc.AddressBook;
	using Monobjc.AppKit;
	
	
	public partial class MyPeoplePickerController {
		
		partial void EditInAB(Id sender);

		partial void GetGroups(Id sender);

		partial void GetRecords(Id sender);

		partial void SelectInAB(Id sender);

		partial void SetGroupSelection(NSButton sender);

		partial void SetMultiRecordSelection(NSButton sender);

		partial void ViewProperty(NSButton sender);

		[IBOutlet()]
		[ObjectiveCIVar("ppView")]
		public virtual ABPeoplePickerView ppView {
			get {
				return this.GetInstanceVariable <ABPeoplePickerView>("ppView");
			}
			set {
				this.SetInstanceVariable <ABPeoplePickerView>("ppView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("editInAB:")]
		public virtual void __EditInAB(Id sender) {
			this.EditInAB(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("getGroups:")]
		public virtual void __GetGroups(Id sender) {
			this.GetGroups(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("getRecords:")]
		public virtual void __GetRecords(Id sender) {
			this.GetRecords(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("selectInAB:")]
		public virtual void __SelectInAB(Id sender) {
			this.SelectInAB(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("setGroupSelection:")]
		public virtual void __SetGroupSelection(NSButton sender) {
			this.SetGroupSelection(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("setMultiRecordSelection:")]
		public virtual void __SetMultiRecordSelection(NSButton sender) {
			this.SetMultiRecordSelection(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("viewProperty:")]
		public virtual void __ViewProperty(NSButton sender) {
			this.ViewProperty(sender);
		}
	}
}
