// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.Fireworks {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class AppController {
		
		partial void ResetSliders(Id sender);

		partial void SlidersMoved(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("animationSpeed")]
		public virtual NSSlider animationSpeed {
			get {
				return this.GetInstanceVariable <NSSlider>("animationSpeed");
			}
			set {
				this.SetInstanceVariable <NSSlider>("animationSpeed", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fireworkGravity")]
		public virtual NSSlider fireworkGravity {
			get {
				return this.GetInstanceVariable <NSSlider>("fireworkGravity");
			}
			set {
				this.SetInstanceVariable <NSSlider>("fireworkGravity", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fireworkRange")]
		public virtual NSSlider fireworkRange {
			get {
				return this.GetInstanceVariable <NSSlider>("fireworkRange");
			}
			set {
				this.SetInstanceVariable <NSSlider>("fireworkRange", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fireworkVelocity")]
		public virtual NSSlider fireworkVelocity {
			get {
				return this.GetInstanceVariable <NSSlider>("fireworkVelocity");
			}
			set {
				this.SetInstanceVariable <NSSlider>("fireworkVelocity", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("fireworkVelocityRange")]
		public virtual NSSlider fireworkVelocityRange {
			get {
				return this.GetInstanceVariable <NSSlider>("fireworkVelocityRange");
			}
			set {
				this.SetInstanceVariable <NSSlider>("fireworkVelocityRange", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("rocketGravity")]
		public virtual NSSlider rocketGravity {
			get {
				return this.GetInstanceVariable <NSSlider>("rocketGravity");
			}
			set {
				this.SetInstanceVariable <NSSlider>("rocketGravity", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("rocketRange")]
		public virtual NSSlider rocketRange {
			get {
				return this.GetInstanceVariable <NSSlider>("rocketRange");
			}
			set {
				this.SetInstanceVariable <NSSlider>("rocketRange", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("rocketVelocity")]
		public virtual NSSlider rocketVelocity {
			get {
				return this.GetInstanceVariable <NSSlider>("rocketVelocity");
			}
			set {
				this.SetInstanceVariable <NSSlider>("rocketVelocity", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("rocketVelocityRange")]
		public virtual NSSlider rocketVelocityRange {
			get {
				return this.GetInstanceVariable <NSSlider>("rocketVelocityRange");
			}
			set {
				this.SetInstanceVariable <NSSlider>("rocketVelocityRange", value);
			}
		}
		
		[IBOutlet()]
		[ObjectiveCIVar("theView")]
		public virtual NSView theView {
			get {
				return this.GetInstanceVariable <NSView>("theView");
			}
			set {
				this.SetInstanceVariable <NSView>("theView", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("resetSliders:")]
		public virtual void __ResetSliders(Id sender) {
			this.ResetSliders(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("slidersMoved:")]
		public virtual void __SlidersMoved(Id sender) {
			this.SlidersMoved(sender);
		}
	}
}
