// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 2.0.50727.1433
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace Monobjc.Samples.AnimatingViews {
	using Monobjc;
	using Monobjc.AppKit;
	
	
	public partial class SimpleLayoutView {
		
		partial void AddABox(Id sender);

		partial void ChangeLayout(Id sender);

		partial void RemoveLastBox(Id sender);

		[IBOutlet()]
		[ObjectiveCIVar("boxColorField")]
		public virtual NSColorWell boxColorField {
			get {
				return this.GetInstanceVariable <NSColorWell>("boxColorField");
			}
			set {
				this.SetInstanceVariable <NSColorWell>("boxColorField", value);
			}
		}
		
		[IBAction()]
		[ObjectiveCMessage("addABox:")]
		public virtual void __AddABox(Id sender) {
			this.AddABox(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("changeLayout:")]
		public virtual void __ChangeLayout(Id sender) {
			this.ChangeLayout(sender);
		}
		
		[IBAction()]
		[ObjectiveCMessage("removeLastBox:")]
		public virtual void __RemoveLastBox(Id sender) {
			this.RemoveLastBox(sender);
		}
	}
}
